contrib/paccache: silence possible output from cd
If CDPATH is set, this could possibly write to stdout.

Signed-off-by: Dave Reisner <dreisner@archlinux.org>
Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/contrib/paccache.in b/contrib/paccache.in
--- a/contrib/paccache.in
+++ b/contrib/paccache.in
@@ -261,7 +261,7 @@ if (( move || delete )); then
 fi
 
 # unlikely that this will fail, but better make sure
-cd "$cachedir" || die "failed to chdir to \`%s'" "$cachedir"
+cd "$cachedir" >/dev/null || die "failed to chdir to \`%s'" "$cachedir"
 
 # note that these results are returned in an arbitrary order from awk, but
 # they'll be resorted (in summarize) iff we have a verbosity level set.
