contrib/pacdiff: error if diffprog is not found
FS#35936

Signed-off-by: Allan McRae <allan@archlinux.org>

diff --git a/contrib/pacdiff.sh.in b/contrib/pacdiff.sh.in
--- a/contrib/pacdiff.sh.in
+++ b/contrib/pacdiff.sh.in
@@ -116,6 +116,11 @@ done
 
 m4_include(../scripts/library/term_colors.sh)
 
+if ! type -p $diffprog >/dev/null; then
+	error "Cannot find the $diffprog binary required for viewing differences."
+	exit 1
+fi
+
 case $(( USE_FIND + USE_LOCATE + USE_PACDB )) in
 	0) USE_PACDB=1;; # set the default search option
 	[^1]) error "Only one search option may be used at a time"
