debugedit: only check for debugedit if we build a package
We only really need debugedit while building the package, while this
check would run if you tried something like `makepkg --verifysource`.
Use the same checks as we have for fakeroot to wrap debugedit so we
don't beg for dependencies we don't need.

Fixes: 3ed08f97ecd5941c3f72e3e94f17826dd959f823

Signed-off-by: Morten Linderud <morten@linderud.pw>

diff --git a/scripts/libmakepkg/executable/debugedit.sh.in b/scripts/libmakepkg/executable/debugedit.sh.in
--- a/scripts/libmakepkg/executable/debugedit.sh.in
+++ b/scripts/libmakepkg/executable/debugedit.sh.in
@@ -29,10 +29,12 @@ source "$MAKEPKG_LIBRARY/util/option.sh"
 executable_functions+=('executable_debugedit')
 
 executable_debugedit() {
-	if check_option "debug" "y"; then
-		if ! type -p debugedit >/dev/null; then
-			error "$(gettext "Cannot find the %s binary required for including source files in debug packages.")" "debugedit"
-			return 1
+	if (( SOURCEONLY || BUILDPKG )); then
+		if check_option "debug" "y"; then
+			if ! type -p debugedit >/dev/null; then
+				error "$(gettext "Cannot find the %s binary required for including source files in debug packages.")" "debugedit"
+				return 1
+			fi
 		fi
 	fi
 }
