don't die on missing package files, just warn (#3535)

diff --git a/scripts/gensync b/scripts/gensync
--- a/scripts/gensync
+++ b/scripts/gensync
@@ -140,7 +140,7 @@ db_write_entry()
 
 if [ $# -lt 2 ]; then
 	usage
-	exit 0
+	exit 1
 fi
 
 if [ "$1" = "-h" -o "$1" = "--help" ]; then
@@ -169,12 +169,14 @@ for file in `find $rootdir/* -name PKGBUILD`; do
 	else
 		pkgfile="$destdir/$pkgname-$pkgver-$pkgrel.pkg.tar.gz"
 	fi
-	[ -f $pkgfile ] || die "missing package file: $pkgfile"
-	csize=`du -b $pkgfile | cut -f1`
-	pkgmd5sum=`get_md5checksum $pkgfile`
-	[ -z $pkgmd5sum ] && die "error generating checksum for $pkgfile"
-	db_write_entry $file
-	[ $? -gt 0 ] && die "error writing entry for $file"
+	if [ -f $pkgfile ]; then
+		csize=`du -b $pkgfile | cut -f1`
+		pkgmd5sum=`get_md5checksum $pkgfile`
+		[ -z $pkgmd5sum ] && die "error generating checksum for $pkgfile"
+		db_write_entry $file || die "error writing entry for $file"
+	else
+		echo "gensync: missing package: $pkgfile" >&2
+	fi
 done
 
 echo "gensync: compressing to $destfile..." >&2
diff --git a/scripts/updatesync b/scripts/updatesync
--- a/scripts/updatesync
+++ b/scripts/updatesync
@@ -157,7 +157,7 @@ delete_entry()
 
 if [ $# -lt 3 ]; then
 	usage
-	exit 0
+	exit 1
 fi
 
 if [ "$1" = "-h" -o "$1" = "--help" ]; then
@@ -210,12 +210,15 @@ if [ "$action" = "upd" ]; then
 	else
 		pkgfile="$destdir/$pkgname-$pkgver-$pkgrel.pkg.tar.gz"
 	fi
-	[ -f $pkgfile ] || die "missing package file: $pkgfile"
-	csize=`du -b $pkgfile | cut -f1`
-	pkgmd5sum=`get_md5checksum $pkgfile`
-	[ -z $pkgmd5sum ] && die "error generating checksum for $pkgfile"
-	echo "updatesync: creating entry for $option" >&2
-	db_write_entry $option || die "error writing entry for $option"
+	if [ -f $pkgfile ]; then
+		csize=`du -b $pkgfile | cut -f1`
+		pkgmd5sum=`get_md5checksum $pkgfile`
+		[ -z $pkgmd5sum ] && die "error generating checksum for $pkgfile"
+		echo "updatesync: creating entry for $option" >&2
+		db_write_entry $option || die "error writing entry for $option"
+	else
+		echo "updatesync: missing package: $pkgfile" >&2
+	fi
 else
 	# DELETE
 	delete_entry $option
