update of translation-help and fix a typo in gensync.
Signed-off-by: Chantry Xavier <shiningxc@gmail.com>

diff --git a/scripts/gensync.sh.in b/scripts/gensync.sh.in
--- a/scripts/gensync.sh.in
+++ b/scripts/gensync.sh.in
@@ -126,7 +126,7 @@ forcepkgs=""
 for file in $(find "$rootdir"/* -name "$BUILDSCRIPT"); do
 	unset pkgname pkgver pkgrel options
 
-	source $file || die "$(gettext "failed to parse parse %s")" $file
+	source $file || die "$(gettext "failed to parse %s")" $file
 	if [ "$arch" = 'any' ]; then
 		CARCH='any'
 	fi
