scripts: do autoconf path replacement right
This should finally get the path replacement in our scripts right. This
is the way the autoconf package itself does it and should not need much
further tweaking.

Threw in a few trailing whitespace corrections from the scripts as well.

Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/gensync.in b/scripts/gensync.in
--- a/scripts/gensync.in
+++ b/scripts/gensync.in
@@ -1,22 +1,23 @@
 #!/bin/bash
-# 
+#
 #   gensync
-#  
+#   @configure_input@
+#
 #   Copyright (c) 2002-2007 by Judd Vinet <jvinet@zeroflux.org>
-#  
+#
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation; either version 2 of the License, or
 #   (at your option) any later version.
-# 
+#
 #   This program is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.
-#  
+#
 #   You should have received a copy of the GNU General Public License
 #   along with this program; if not, write to the Free Software
-#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
+#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
 #   USA.
 #
 
@@ -37,9 +38,9 @@ usage() {
 	echo
 	echo "note: The <destfile> name is important.  It must be of the form"
 	echo "      {treename}.db.tar.gz where {treename} is the name of the custom"
-	echo "      package repository you configured in @SYSCONFDIR@/pacman.conf.  The"
+	echo "      package repository you configured in @sysconfdir@/pacman.conf.  The"
 	echo "      generated database must reside in the same directory as your"
-	echo "      custom packages (also configured in @SYSCONFDIR@/pacman.conf)"
+	echo "      custom packages (also configured in @sysconfdir@/pacman.conf)"
 	echo
 	echo "example:  gensync /var/abs/local /home/mypkgs/custom.db.tar.gz"
 	echo
@@ -94,10 +95,10 @@ if [ $# -lt 2 ]; then
 fi
 
 # source system and user makepkg.conf
-if [ -r @SYSCONFDIR@/makepkg.conf ]; then
-	source @SYSCONFDIR@/makepkg.conf
+if [ -r @sysconfdir@/makepkg.conf ]; then
+	source @sysconfdir@/makepkg.conf
 else
-	echo "ERROR: @SYSCONFDIR@/makepkg.conf not found. Can not continue." >&2
+	echo "ERROR: @sysconfdir@/makepkg.conf not found. Can not continue." >&2
 	exit 1 # $E_CONFIG_ERROR # TODO: error codes
 fi
 
