Tidy up usage of makepkg.conf
Moved the following variables into /etc/makepkg.conf
	* BUILDSCRIPT
	* PKGEXT
	* DB_COMPRESSION
	* DB_CHECKSUMS

Cleaned up sourcing of /etc/makepkg.conf in scripts and source
~/.makepkg.conf if it exists.

Signed-off-by: Andrew Fyfe <andrew@neptune-one.net>
Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/gensync b/scripts/gensync
--- a/scripts/gensync
+++ b/scripts/gensync
@@ -22,6 +22,8 @@
 
 myver='3.0.0'
 
+# functions
+
 usage() {
 	echo "gensync $myver"
 	echo "usage: $0 <root> <destfile> [package_directory]"
@@ -45,11 +47,6 @@ usage() {
 	exit 0
 }
 
-BUILDSCRIPT="PKGBUILD"
-PKGEXT="pkg.tar.gz" 
-
-source /etc/makepkg.conf
-
 error () {
 	echo "==> ERROR: $*" >&2
 }
@@ -70,6 +67,8 @@ check_force () {
 	false
 }
 
+# PROGRAM START
+
 if [ $# -lt 2 ]; then
 	usage
 	exit 1
@@ -79,6 +78,19 @@ if [ "$1" = "-h" -o "$1" = "--help" ]; then
 	usage
 	exit 0
 fi
+
+# source system and user makepkg.conf
+if [ -r /etc/makepkg.conf ]; then
+	source /etc/makepkg.conf
+else
+	echo "ERROR: /etc/makepkg.conf not found. Can not continue." >&2
+	exit 1 # $E_CONFIG_ERROR # TODO: error codes
+fi
+
+if [ -r ~/.makepkg.conf ]; then
+	source ~/.makepkg.conf
+fi
+
 
 d=$(dirname $1)
 rootdir="$(cd $d && pwd)/$(basename $1)"
diff --git a/scripts/makepkg.in b/scripts/makepkg.in
--- a/scripts/makepkg.in
+++ b/scripts/makepkg.in
@@ -36,11 +36,16 @@ export TEXTDOMAINDIR
 myver='3.0.0'
 startdir=$(pwd)
 
-BUILDSCRIPT="PKGBUILD"
-PKGEXT="pkg.tar.gz"
-
-source "/etc/abs/abs.conf"
-SRCROOT="$ABSROOT"
+# Only use ABSROOT if we haven't been passed a SRCROOT on the command line.
+if [ -z "$SRCROOT" ]; then
+	if [ -r /etc/abs/abs.conf ]; then
+		source /etc/abs/abs.conf
+	fi
+	if [ -r ~/.abs.conf ]; then
+		source ~/.abs.conf
+	fi
+	SRCROOT=$ABSROOT
+fi	
 
 # Options
 CLEANUP=0
@@ -418,16 +423,16 @@ ARGLIST=$@
 _PKGDEST=${PKGDEST}
 _SRCDEST=${SRCDEST}
 
-#Source makepkg.conf; fail if it is not found
-if [ -f /etc/makepkg.conf ]; then
+# Source makepkg.conf; fail if it is not found
+if [ -r /etc/makepkg.conf ]; then
 	source /etc/makepkg.conf
 else
 	error "$(gettext "/etc/makepkg.conf not found. cannot continue")"
-	exit 1
+	exit 1 # $E_CONFIG_ERROR # TODO: error codes
 fi
 
-#Source user-specific makepkg.conf overrides
-if [ -f ~/.makepkg.conf ]; then
+# Source user-specific makepkg.conf overrides
+if [ -r ~/.makepkg.conf ]; then
 	source ~/.makepkg.conf
 fi
 
diff --git a/scripts/repo-remove b/scripts/repo-remove
--- a/scripts/repo-remove
+++ b/scripts/repo-remove
@@ -23,9 +23,6 @@ myver='3.0.0'
 
 FORCE=0
 REPO_DB_FILE=""
-
-DB_COMPRESSION="gz" #TODO this is gross
-DB_CHECKSUMS=(md5)
 TMP_DIR=""
 
 # print usage instructions
@@ -78,6 +75,18 @@ fi
 if [ $# -lt 2 ]; then
 	usage
 	exit 1
+fi
+
+# source system and user makepkg.conf
+if [ -r /etc/makepkg.conf ]; then
+	source /etc/makepkg.conf
+else
+	echo "ERROR: /etc/makepkg.conf not found. Can not continue." >&2
+	exit 1 # $E_CONFIG_ERROR # TODO: error codes
+fi
+
+if [ -r ~/.makepkg.conf ]; then
+	source ~/.makepkg.conf
 fi
 
 # main routine
diff --git a/scripts/updatesync b/scripts/updatesync
--- a/scripts/updatesync
+++ b/scripts/updatesync
@@ -23,6 +23,8 @@
 
 myver='3.0.0'
 
+# functions
+
 usage() {
 	echo "updatesync $myver"
 	echo "usage: $0 <action> <destfile> <option> [package_directory]"
@@ -47,11 +49,6 @@ usage() {
 	exit 0
 }
 
-BUILDSCRIPT="PKGBUILD"
-PKGEXT="pkg.tar.gz" 
-
-source /etc/makepkg.conf
-
 error () {
 	echo "==> ERROR: $*" >&2
 }
@@ -72,6 +69,8 @@ check_force () {
 	false
 }
 
+# PROGRAM START
+
 if [ $# -lt 3 ]; then
 	usage
 	exit 1
@@ -80,6 +79,18 @@ fi
 if [ "$1" = "-h" -o "$1" = "--help" ]; then
 	usage
 	exit 0
+fi
+
+# source system and user makepkg.conf
+if [ -r /etc/makepkg.conf ]; then
+	source /etc/makepkg.conf
+else
+	echo "ERROR: /etc/makepkg.conf not found. Can not continue." >&2
+	exit 1 # $E_CONFIG_ERROR # TODO: error codes
+fi
+
+if [ -r ~/.makepkg.conf ]; then
+	source ~/.makepkg.conf
 fi
 
 if [ "$1" != "upd" -a "$1" != "del" ]; then
