makepkg: fix svn repo extraction
Copy SVN repos rather than using "svn export" to keep all anotation
files in the repo for build scripts that use (e.g.) "svin info".

Signed-off-by: Allan McRae <allan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -743,7 +743,7 @@ extract_svn() {
 	if [[ -n $fragment ]]; then
 		case ${fragment%%=*} in
 			revision)
-				ref=('-r' "${fragment##*=}")
+				ref="${fragment##*=}"
 				;;
 			*)
 				error "$(gettext "Unrecognized reference: %s")" "${fragment}"
@@ -752,9 +752,14 @@ extract_svn() {
 		esac
 	fi
 
-	if ! svn export ${ref[@]} "$dir"; then
-		error "$(gettext "Failure while creating working copy of %s %s repo")" "${repo}" "svn"
-		plain "$(gettext "Aborting...")"
+	cp -a "$dir" .
+
+	if [[ -n ${ref} ]]; then
+		cd_safe "$(get_filename "$netfile")"
+		if ! svn update -r ${ref}; then
+			error "$(gettext "Failure while creating working copy of %s %s repo")" "${repo}" "svn"
+			plain "$(gettext "Aborting...")"
+		fi
 	fi
 
 	popd &>/dev/null
