makepkg: Fix output color codes for real
Make sure we reset both the bold attribute and the color attributes when it
is necessary.

Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -67,7 +67,7 @@ PACMAN_OPTS=
 plain() {
 	local mesg=$1; shift
 	if [ -t 2 -a ! "$USE_COLOR" = "n" -a "$(check_buildenv color)" = "y" ]; then
-		printf "\033[1;1m    ${mesg}\033[0m\n" "$@" >&2
+		printf "\033[1;1m    ${mesg}\033[1;0m\n" "$@" >&2
 	else
 		printf "    ${mesg}\n" "$@" >&2
 	fi
@@ -76,7 +76,7 @@ plain() {
 msg() {
 	local mesg=$1; shift
 	if [ -t 2 -a ! "$USE_COLOR" = "n" -a "$(check_buildenv color)" = "y" ]; then
-		printf "\033[1;32m==>\033[1;1m ${mesg}\033[0m\n" "$@" >&2
+		printf "\033[1;32m==>\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
 	else
 		printf "==> ${mesg}\n" "$@" >&2
 	fi
@@ -85,7 +85,7 @@ msg() {
 msg2() {
 	local mesg=$1; shift
 	if [ -t 2 -a ! "$USE_COLOR" = "n" -a "$(check_buildenv color)" = "y" ]; then
-		printf "\033[1;34m  ->\033[1;1m ${mesg}\033[0m\n" "$@" >&2
+		printf "\033[1;34m  ->\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
 	else
 		printf "  -> ${mesg}\n" "$@" >&2
 	fi
@@ -94,7 +94,7 @@ msg2() {
 warning() {
 	local mesg=$1; shift
 	if [ -t 2 -a ! "$USE_COLOR" = "n" -a "$(check_buildenv color)" = "y" ]; then
-		printf "\033[1;33m==> $(gettext "WARNING:")\033[1;1m ${mesg}\033[0m\n" "$@" >&2
+		printf "\033[1;33m==> $(gettext "WARNING:")\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
 	else
 		printf "==> $(gettext "WARNING:") ${mesg}\n" "$@" >&2
 	fi
@@ -103,7 +103,7 @@ warning() {
 error() {
 	local mesg=$1; shift
 	if [ -t 2 -a ! "$USE_COLOR" = "n" -a "$(check_buildenv color)" = "y" ]; then
-		printf "\033[1;31m==> $(gettext "ERROR:")\033[1;1m ${mesg}\033[0m\n" "$@" >&2
+		printf "\033[1;31m==> $(gettext "ERROR:")\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
 	else
 		printf "==> $(gettext "ERROR:") ${mesg}\n" "$@" >&2
 	fi
