Check if pkgdir exists in create_package
Signed-off-by: Dag Odenhall <dag.odenhall@gmail.com>
Signed-off-by: Andrew Fyfe <andrew@neptune-one.net>
Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/makepkg.in b/scripts/makepkg.in
--- a/scripts/makepkg.in
+++ b/scripts/makepkg.in
@@ -502,6 +502,11 @@ tidy_install() {
 }
 
 create_package() {
+	if [ ! -d "$pkgdir" ]; then
+		error "$(gettext "Missing pkg/ directory, aborting...")"
+		exit 1 # $E_MISSING_PKGDIR # TODO: error code
+	fi
+
 	cd "$startdir"/pkg
 	msg "$(gettext "Creating package...")"
 
