makepkg: detect incorrect usage of provides array
Using > or < in the provides array is wrong so make it cause an error.
Fixes FS#12540.

Also, use bash substitution rather than spawning new processes where
possible in the error checking.  Move split package detection to a
better position.

Signed-off-by: Allan McRae <allan@archlinux.org>
[Dan: backport to maint]
Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -1439,11 +1439,11 @@ if [ -z "$pkgrel" ]; then
 	error "$(gettext "%s is not allowed to be empty.")" "pkgrel"
 	exit 1
 fi
-if [ $(echo "$pkgver" | grep '-') ]; then
+if [ "$pkgver" != "${pkgver//-/}" ]; then
 	error "$(gettext "%s is not allowed to contain hyphens.")" "pkgver"
 	exit 1
 fi
-if [ $(echo "$pkgrel" | grep '-') ]; then
+if [ "$pkgrel" != "${pkgrel//-/}" ]; then
 	error "$(gettext "%s is not allowed to contain hyphens.")" "pkgrel"
 	exit 1
 fi
@@ -1464,6 +1464,14 @@ if ! in_array $CARCH ${arch[@]}; then
 		plain "$(gettext "such as arch=('%s').")" "$CARCH"
 	fi
 fi
+
+for provide in ${provides[@]}; do
+	if [ $provide != ${provide//</} -o $provide != ${provide//>/} ]; then
+		error "$(gettext "Provides array cannot contain comparison (< or >) operators.")"
+		exit 1
+	fi
+done
+unset provide
 
 if [ "$install" -a ! -f "$install" ]; then
 	error "$(gettext "Install scriptlet (%s) does not exist.")" "$install"
