makepkg: ensure PKGBUILD does not contain CRLF characters
Do a simple check before sourcing the file to ensure we are a valid bash
script.

Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -1354,6 +1354,12 @@ if [ ! -f "$BUILDSCRIPT" ]; then
 		# PKGBUILD passed through a pipe
 		BUILDSCRIPT=/dev/stdin
 	fi
+else
+	crlftest=$(file $BUILDSCRIPT | grep -F 'CRLF' || true)
+	if [ "$crlftest" != "" ]; then
+		error "$(gettext "%s contains CRLF characters and cannot be sourced.")" "$BUILDSCRIPT"
+		exit 1
+	fi
 fi
 
 source "$BUILDSCRIPT"
