makepkg: Use SKIP in checksum to skip integrity check
Using the value of "SKIP" in the checksum array will cause that
integrity check to be skipped.  This makes building packages that
rely on user configurable sources less painful.

Based-on-patch-by: Dan McGee <dan@archlinux.org>
Based-on-patch-by: David Campbell <davekong@archlinux.us>
Signed-off-by: Allan McRae <allan@archlinux.org>
Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -663,14 +663,18 @@ check_checksums() {
 				fi
 
 				if (( $found )) ; then
-					local expectedsum=$(tr '[:upper:]' '[:lower:]' <<< "${integrity_sums[$idx]}")
-					local realsum="$(openssl dgst -${integ} "$file")"
-					realsum="${realsum##* }"
-					if [[ $expectedsum = $realsum ]]; then
-						echo "$(gettext "Passed")" >&2
+					if [[ ${integrity_sums[$idx]} = 'SKIP' ]]; then
+						echo "$(gettext "Skipped")" >&2
 					else
-						echo "$(gettext "FAILED")" >&2
-						errors=1
+						local expectedsum=$(tr '[:upper:]' '[:lower:]' <<< "${integrity_sums[$idx]}")
+						local realsum="$(openssl dgst -${integ} "$file")"
+						realsum="${realsum##* }"
+						if [[ $expectedsum = $realsum ]]; then
+							echo "$(gettext "Passed")" >&2
+						else
+							echo "$(gettext "FAILED")" >&2
+							errors=1
+						fi
 					fi
 				fi
 
