Check status of final tar/compress package creation for final status (FS#3382)

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -880,6 +880,11 @@ else
 fi
 $cmd | sort >../filelist
 
+if [ ${PIPESTATUS[0]} -gt 0 ]; then
+    error "Failed to create package file."
+    exit ${PIPESTATUS[0]}
+fi
+
 cd $startdir
 if [ "$CLEANUP" = "1" ]; then
 	msg "Cleaning up..."
