makepkg: rework --skipinteg
The current --skipinteg is a bit weird.  It does not skip integrity
checks, but instead does them and prints a warning. Change this
behaviour to actually skipping the checks.

Signed-off-by: Allan McRae <allan@archlinux.org>
Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -636,12 +636,8 @@ check_checksums() {
 	done
 
 	if (( ! correlation )); then
-		if (( SKIPINTEG )); then
-			warning "$(gettext "Integrity checks are missing.")"
-		else
-			error "$(gettext "Integrity checks are missing.")"
-			exit 1 # TODO: error code
-		fi
+		error "$(gettext "Integrity checks are missing.")"
+		exit 1 # TODO: error code
 	fi
 }
 
@@ -1970,7 +1966,11 @@ elif (( REPKG )); then
 	fi
 else
 	download_sources
-	check_checksums
+	if (( ! SKIPINTEG )); then
+		check_checksums
+	else
+		warning "$(gettext "Skipping integrity checks.")"
+	fi
 	extract_sources
 fi
 
