scripts/makepkg.in: Add gettext translation for WARNING and ERROR.
Signed-off-by: Andrew Fyfe <andrew@neptune-one.net>

diff --git a/scripts/makepkg.in b/scripts/makepkg.in
--- a/scripts/makepkg.in
+++ b/scripts/makepkg.in
@@ -88,18 +88,18 @@ msg2() {
 warning() {
 	local mesg=$1; shift
 	if [ ! "$USE_COLOR" = "n" -a "$(check_buildenv color)" = "y" ]; then
-		printf "\033[1;33m==> WARNING:\033[1;37m ${mesg}\033[0m\n" "$@" >&2
+		printf "\033[1;33m==> $(gettext "WARNING:")\033[1;37m ${mesg}\033[0m\n" "$@" >&2
 	else
-		printf "==> WARNING: ${mesg}\n" "$@" >&2
+		printf "==> $(gettext "WARNING:") ${mesg}\n" "$@" >&2
 	fi
 }
 
 error() {
 	local mesg=$1; shift
 	if [ ! "$USE_COLOR" = "n" -a "$(check_buildenv color)" = "y" ]; then
-		printf "\033[1;31m==> ERROR:\033[1;37m ${mesg}\033[0m\n" "$@" >&2
+		printf "\033[1;31m==> $(gettext "ERROR:")\033[1;37m ${mesg}\033[0m\n" "$@" >&2
 	else
-		printf "==> ERROR: ${mesg}\n" "$@" >&2
+		printf "==> $(gettext "ERROR:") ${mesg}\n" "$@" >&2
 	fi
 }
 
