makepkg: clarify aborting on packaging failure
When makepkg catches a command failure it currently prints "Aborting..."
and exits.  Clarify the reason for aborting from packaging is a failure
during one of the PKGBUILDs functions.

Signed-off-by: Allan McRae <allan@archlinux.org>
Signed-off-by: Dan McGee <dan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -721,6 +721,7 @@ error_function() {
 	fi
 	# first exit all subshells, then print the error
 	if (( ! BASH_SUBSHELL )); then
+		error "$(gettext "A failure occurred in %s().")" "$1"
 		plain "$(gettext "Aborting...")"
 		remove_deps
 	fi
@@ -768,7 +769,7 @@ run_function() {
 		tee "$BUILDLOG" < "$logpipe" &
 		exec 1>"$logpipe" 2>"$logpipe"
 		restoretrap=$(trap -p ERR)
-		trap 'error_function' ERR
+		trap 'error_function $pkgfunc' ERR
 		$pkgfunc 2>&1
 		eval $restoretrap
 		sync
@@ -776,7 +777,7 @@ run_function() {
 		rm "$logpipe"
 	else
 		restoretrap=$(trap -p ERR)
-		trap 'error_function' ERR
+		trap 'error_function $pkgfunc' ERR
 		$pkgfunc 2>&1
 		eval $restoretrap
 	fi
