makepkg: Exit on failure within build() or package() functions
Errors in build() functions were only fatal, if "--log" was enabled. Errors in
package() functions were never fatal. Piping these functions through "cat -"
triggers error trapping. This prevents the need for "|| return 1" usage in
PKGBUILDs.

Original-patch-by: Juergen Hoetzel <juergen@archlinux.org>
Signed-off-by: Allan McRae <allan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -718,8 +718,10 @@ run_build() {
 
 		build 2>&1 | tee "$BUILDLOG"; ret=${PIPESTATUS[0]}
 	else
-		build 2>&1 || ret=$?
+		# piping to cat ensures makepkg fails on any build error
+		build 2>&1 | cat -; ret=${PIPESTATUS[0]}
 	fi
+
 	# reset our shell options
 	eval "$shellopts"
 
@@ -772,12 +774,12 @@ run_package() {
 		exec 3>&1
 		tee "$BUILDLOG" < "$logpipe" &
 		exec 1>"$logpipe" 2>"$logpipe"
-		$pkgfunc 2>&1 || ret=$?
+		$pkgfunc 2>&1 | cat -; ret=${PIPESTATUS[0]}
 		sync
 		exec 1>&3 2>&3 3>&-
 		rm "$logpipe"
 	else
-		$pkgfunc 2>&1 || ret=$?
+		$pkgfunc 2>&1 | cat -; ret=${PIPESTATUS[0]}
 	fi
 
 	if [ $ret -gt 0 ]; then
