makepkg: Move parseopts from library to libmakepkg
parseopts is used in makepkg and other scripts such as pacman-key as a
getopt replacement.

Instead of including it in those scripts via a macro, move it to
libmakepkg/util/parseopts.sh and have scripts source this file where
appropriate.

To keep the parseopts test, a new variable was introduced:
PM_LIBMAKEPKG_DIR

Signed-off-by: Alad Wenter <alad@archlinux.info>
Signed-off-by: Allan McRae <allan@archlinux.org>

diff --git a/scripts/libmakepkg/util/parseopts.sh.in b/scripts/libmakepkg/util/parseopts.sh.in
--- a/scripts/libmakepkg/util/parseopts.sh.in
+++ b/scripts/libmakepkg/util/parseopts.sh.in
@@ -1,4 +1,40 @@
-# getopt-like parser
+#!/bin/bash
+#
+#   parseopts.sh - getopt_long-like parser
+#
+#   Copyright (c) 2012-2016 Pacman Development Team <pacman-dev@archlinux.org>
+#
+#   This program is free software; you can redistribute it and/or modify
+#   it under the terms of the GNU General Public License as published by
+#   the Free Software Foundation; either version 2 of the License, or
+#   (at your option) any later version.
+#
+#   This program is distributed in the hope that it will be useful,
+#   but WITHOUT ANY WARRANTY; without even the implied warranty of
+#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#   GNU General Public License for more details.
+#
+#   You should have received a copy of the GNU General Public License
+#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+# A getopt_long-like parser which portably supports longopts and
+# shortopts with some GNU extensions. It does not allow for options
+# with optional arguments. For both short and long opts, options
+# requiring an argument should be suffixed with a colon. After the
+# first argument containing the short opts, any number of valid long
+# opts may be be passed. The end of the options delimiter must then be
+# added, followed by the user arguments to the calling program.
+#
+# Recommended Usage:
+#   OPT_SHORT='fb:z'
+#   OPT_LONG=('foo' 'bar:' 'baz')
+#   if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
+#     exit 1
+#   fi
+#   set -- "${OPTRET[@]}"
+# Returns:
+#   0: parse success
+#   1: parse failure (error message supplied)
 parseopts() {
 	local opt= optarg= i= shortopts=$1
 	local -a longopts=() unused_argv=()
@@ -34,7 +70,7 @@ parseopts() {
 				return 255 ;;
 			*)
 				# fail, ambiguous match
-				printf "@SCRIPTNAME@: $(gettext "option '%s' is ambiguous; possibilities:")" "--$1"
+				printf "${0##*/}: $(gettext "option '%s' is ambiguous; possibilities:")" "--$1"
 				printf " '%s'" "${longmatch[@]%:}"
 				printf '\n'
 				return 254 ;;
@@ -53,7 +89,7 @@ parseopts() {
 
 					# option doesn't exist
 					if [[ $shortopts != *$opt* ]]; then
-						printf "@SCRIPTNAME@: $(gettext "invalid option") -- '%s'\n" "$opt" >&2
+						printf "${0##*/}: $(gettext "invalid option") -- '%s'\n" "$opt" >&2
 						OPTRET=(--)
 						return 1
 					fi
@@ -72,7 +108,7 @@ parseopts() {
 							break
 						# parse failure
 						else
-							printf "@SCRIPTNAME@: $(gettext "option requires an argument") -- '%s'\n" "$opt" >&2
+							printf "${0##*/}: $(gettext "option requires an argument") -- '%s'\n" "$opt" >&2
 							OPTRET=(--)
 							return 1
 						fi
@@ -86,7 +122,7 @@ parseopts() {
 					0)
 						# parse failure
 						if [[ $optarg ]]; then
-							printf "@SCRIPTNAME@: $(gettext "option '%s' does not allow an argument")\n" "--$opt" >&2
+							printf "${0##*/}: $(gettext "option '%s' does not allow an argument")\n" "--$opt" >&2
 							OPTRET=(--)
 							return 1
 						# --longopt
@@ -104,7 +140,7 @@ parseopts() {
 							shift
 						# parse failure
 						else
-							printf "@SCRIPTNAME@: $(gettext "option '%s' requires an argument")\n" "--$opt" >&2
+							printf "${0##*/}: $(gettext "option '%s' requires an argument")\n" "--$opt" >&2
 							OPTRET=(--)
 							return 1
 						fi
@@ -116,7 +152,7 @@ parseopts() {
 						;;
 					255)
 						# parse failure
-						printf "@SCRIPTNAME@: $(gettext "invalid option") '--%s'\n" "$opt" >&2
+						printf "${0##*/}: $(gettext "invalid option") '--%s'\n" "$opt" >&2
 						OPTRET=(--)
 						return 1
 						;;
