makepkg: move config loading into libmakepkg
When scripting/automating around makepkg, it is sometimes desirable to
know how makepkg will be configured to operate. One example is the
archlinux devtools, which must forward select makepkg.conf variables
into a build chroot (for example PACKAGER) or use those variables itself
(for example {SRC,PKG,LOG}DEST).

The configuration file can be in up to 3 places, and should be capable
of being overridden via environment variables. It is sufficiently
complex to represent distinct functionality, and sufficiently useful to
merit easy accessibility in other scripts, therefore, let us move it
into a publicly exposed utility library.

Signed-off-by: Eli Schwartz <eschwartz@archlinux.org>
Signed-off-by: Allan McRae <allan@archlinux.org>

diff --git a/scripts/libmakepkg/util/util.sh.in b/scripts/libmakepkg/util/util.sh.in
--- a/scripts/libmakepkg/util/util.sh.in
+++ b/scripts/libmakepkg/util/util.sh.in
@@ -24,6 +24,7 @@ LIBMAKEPKG_UTIL_UTIL_SH=1
 
 LIBRARY=${LIBRARY:-'@libmakepkgdir@'}
 
+source "$LIBRARY/util/error.sh"
 source "$LIBRARY/util/message.sh"
 
 ##
@@ -97,4 +98,17 @@ ensure_writable_dir() {
 	fi
 
 	return 0
+}
+
+# source a file and fail if it does not succeed
+source_safe() {
+	local shellopts=$(shopt -p extglob)
+	shopt -u extglob
+
+	if ! source "$@"; then
+		error "$(gettext "Failed to source %s")" "$1"
+		exit $E_MISSING_FILE
+	fi
+
+	eval "$shellopts"
 }
